services:
  - type: web
    name: bulutmesaj-backend
    env: docker
    buildCommand: docker build -t bulutmesaj-backend .
    startCommand: docker run -p $PORT:80 bulutmesaj-backend
    envVars:
      - key: NODE_ENV
        value: production 