services:
  - type: web
    name: bulutmesaj-backend
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2
    envVars:
      - key: NODE_ENV
        value: production 